### ISSUE TITLE
Docker 1.10 issue

### ISSUE THREAD

**Issue by emilevauge** [mesosphere/docker-containers#40]
Hi,
It seems that latest `mesosphere/mesos-slave:0.26.0-0.2.145.ubuntu1404` has an issue with Docker 1.10.
Using this compose file to launch Mesos+Marathon:

```
zk:
  image: bobrik/zookeeper
  net: host
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
  net: host
  environment:
    MESOS_ZK: zk://127.0.0.1:2181/mesos
    MESOS_HOSTNAME: 127.0.0.1
    MESOS_IP: 127.0.0.1
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos

slave:
  image: mesosphere/mesos-slave:0.26.0-0.2.145.ubuntu1404
  net: host
  pid: host
  privileged: true
  environment:
    MESOS_MASTER: zk://127.0.0.1:2181/mesos
    MESOS_HOSTNAME: 127.0.0.1
    MESOS_IP: 127.0.0.1
    MESOS_CONTAINERIZERS: docker,mesos
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/bin/docker:/usr/bin/docker:ro
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro
    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  image: mesosphere/marathon:v0.13.0
  net: host
  environment:
    MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    MARATHON_ZK: zk://127.0.0.1:2181/marathon
    MARATHON_HOSTNAME: 127.0.0.1
  command: --event_subscriber http_callback
```

Mesos slave exits with an error on docker version:

```
I0210 13:11:48.041368 18353 main.cpp:190] Build: 2015-12-16 23:04:39 by root
I0210 13:11:48.047538 18353 main.cpp:192] Version: 0.26.0
I0210 13:11:48.047550 18353 main.cpp:195] Git tag: 0.26.0
I0210 13:11:48.047561 18353 main.cpp:199] Git SHA: d3717e5c4d1bf4fca5c41cd7ea54fae489028faa
Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127
```

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```
