### ISSUE TITLE
Initial launch instructions are incorrect

### ISSUE THREAD

**Issue by vito-c** [mesosphere/docker-containers#61]
```
OS X El Capitan 10.11.5
```
```
$ docker --version
Docker version 1.12.0-rc2, build 906eacd, experimental
```
Steps To Reproduce:
- Launch zookeeper: https://github.com/mesosphere/docker-containers/blob/master/mesos/README.md#launch-exhibitor-zookeeper
- Launch mesos master: https://github.com/mesosphere/docker-containers/blob/master/mesos/README.md#launch-mesos-master
- Launch mesos slave: https://github.com/mesosphere/docker-containers/blob/master/mesos/README.md#launch-mesos-slave

Actual Result:
Mesos slave and mesos master both fail with this result
```
$ docker logs mesos_master
Failed to obtain the IP address for 'moby'; the DNS service may not be able to resolve it: Name or service not known
```

**Comment by aba182** [comment]
I am having this same problem current with docker for mac:

OS X EL CAPITAN 10.11.5:

docker --version
Docker version 1.12.0-rc4, build e4a0dbc, experimental

`$ docker run -d --net=host   -e MESOS_PORT=5050   -e MESOS_ZK=zk://127.0.0.1:2181/mesos   -e MESOS_QUORUM=1   -e MESOS_REGISTRY=in_memory   -e MESOS_LOG_DIR=/var/log/mesos   -e MESOS_WORK_DIR=/var/tmp/mesos   -v "$(pwd)/log/mesos:/var/log/mesos"   -v "$(pwd)/tmp/mesos:/var/tmp/mesos"   mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404
cac9856dff14be117fab05d173c2425c354704ecab49b625c4fd9058aeb91458

docker logs cac
Failed to obtain the IP address for 'moby'; the DNS service may not be able to resolve it: Temporary failure in name resolution`

Still investigating this. I even added 'moby' to /etc/hosts and can ping it in hopes to make the container happy:

`$ cat /etc/hosts
...
127.0.0.1	localhost,moby
...`

`$ ping moby
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.048 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.118 ms`

**Comment by atamanroman** [comment]
Same here. Mesos master can't start because hostname 'moby' does not resolve. Have a look at my docker-compose:

```
version: '2'
services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    network_mode: 'host'
  mesosmaster:
    image: mesosphere/mesos-master:1.0.1-rc1
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - './mesos/log:/var/log/mesos'
      - './mesos/tmp:/var/tmp/mesos'
    network_mode: 'host'
```

>
❯ docker-compose up zookeeper
...
❯ docker-compose up mesosmaster
Starting mesos_mesosmaster_1
Attaching to mesos_mesosmaster_1
mesosmaster_1  | WARNING: Logging before InitGoogleLogging() is written to STDERR
mesosmaster_1  | I0903 21:50:15.317561     1 main.cpp:263] Build: 2016-08-12 20:49:51 by ubuntu
mesosmaster_1  | I0903 21:50:15.317672     1 main.cpp:264] Version: 1.0.1
mesosmaster_1  | I0903 21:50:15.317677     1 main.cpp:267] Git tag: 1.0.1-rc1
mesosmaster_1  | I0903 21:50:15.317682     1 main.cpp:271] Git SHA: 3611eb0b7eea8d144e9b2e840e0ba16f2f659ee3
mesosmaster_1  | Failed to obtain the IP address for 'moby'; the DNS service may not be able to resolve it: Name or service not known
mesos_mesosmaster_1 exited with code 1
